package edu.ucam.enums;

public enum ErrorType {
	ERROR_TYPE,
	NO_ERROR,
	ERROR,
	PARAMETER_NULL,
	JDBC_ERROR_CONNECTION,
	USER_EXISTS,
	USER_DONT_EXISTS,
	LOGIN_ERROR,
	PASSWORD_DONT_MATCHES,
	ACCESS_DENIED,
	PRODUCT_EXISTS, 
	VIDEOGAME_EXISTS;
}
